```{r}
setwd("~/Documents/uw/2015Fall/Stat424/project")
response=read.csv('response.csv',header=T)
A=rep(rep(c(-1,1),8),3)
B=rep(rep(c(-1,-1,1,1),4),3)
C=rep(rep(c(-1,-1,-1,-1,1,1,1,1),2),3)
D=rep(c(rep(1,8),rep(-1,8)),3)
blocks=as.factor(response$block)

diff=read.csv('recall-judge.csv',header=F)
diff=diff$V1
data=data.frame(A=A,B=B,C=C,D=D,blocks=blocks,metamemo=response$MetaMem,recall=response$recall,diff=diff)
attach(data)
```
block effect
```{r, echo=FALSE}
model.blk=lm(metamemo~A*B*C*D+blocks,data=data)
summary(aov(model.blk))
qqnorm(model.blk$resid)
qqline(model.blk$resid)
plot(model.blk$fitted,model.blk$resid)

model.blk2=lm(recall~A*B*C*D+blocks,data=data)
summary(aov(model.blk2))
qqnorm(model.blk2$resid)
qqline(model.blk2$resid)
plot(model.blk2$fitted,model.blk2$resid)

model.blk3=lm(diff~A*B*C*D+blocks,data=data)
summary(aov(model.blk3))
plot(model.blk3$fitted,model.blk3$resid)
```
main effects
```{r}
metamemo=matrix(data$metamemo,nrow=16,ncol=3,byrow=F)
meanmeta=apply(metamemo,1,mean)
recall=matrix(data$recall,ncol=3,byrow=F)
meanrec=apply(recall,1,mean)
diff=matrix(data$diff,ncol=3,byrow=F)
meandiff=apply(diff,1,mean)

A=rep(c(-1,1),8)
B=rep(c(-1,-1,1,1),4)
C=rep(c(-1,-1,-1,-1,1,1,1,1),2)
D=c(rep(1,8),rep(-1,8))

out.meta=lm(meanmeta~A*B*C*D)
effectsMETA=2*out.meta$coef[-1]
plot(out.meta$fitted,out.meta$resid)


out.rec=lm(meanrec~A*B*C*D)
effectsREC=2*out.rec$coef[-1]
plot(out.rec$fitted,out.rec$resid)

out.diff=lm(meandiff~A*B*C*D)
effectsDiff=2*out.diff$coef[-1]

```
transformation
```{r}
model.blk=lm(1/sqrt(data$metamemo)~A*B*C*D+blocks)
summary(aov(model.blk))
qqnorm(model.blk$resid)
qqline(model.blk$resid)

#no transformation
model.blk2=lm(data$recall~A*B*C*D+blocks)
summary(aov(model.blk2))
qqnorm(model.blk2$resid)
qqline(model.blk2$resid)


model.blk3=lm(1/sqrt(diff)~A*B*C*D+blocks)
summary(aov(model.blk3))

```

